# Generated by Django 2.2 on 2022-03-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_model',
            new_name='Product_model',
        ),
    ]
