# Generated by Django 2.2 on 2022-03-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220301_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_model',
        ),
    ]
