# Generated by Django 2.2 on 2022-03-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_model',
        ),
    ]
